Repository weseek/awesome-database-backup, pull requests merged in 2024-04, with the labels that each got.

#607 fix: (devcontainer) add "-y" when running "apt-get install"
  .devcontainer/Dockerfile
Labels: bug

#608 support: Merge dependent libs automatically
  .github/release-drafter.yml
  .github/workflows/misc-pr_to_master.yaml
  .github/workflows/release-prepare_next_master.yaml
  .mergify
Labels: support

#610 fix: Mergify configs
  .mergify.yml
Labels: exclude from changelog, type/bug

#611 fix: Override rules of branch protection
  .mergify.yml
Labels: exclude from changelog, type/bug

#612 fix: Automatically approve PRs made by dependabot
  .mergify.yml
Labels: exclude from changelog, type/bug

#621 support: Change labels of PR by dependabot
  .github/dependabot.yml
Labels: flag/exclude-from-changelog, type/support
